### ISSUE TITLE
ggtree app demo crashes

### ISSUE THREAD

**Issue by friedue** [cpsievert/shiny_apps#10]
both, Safari and Firefox, no luck using this link: http://104.131.111.111:3838/ggtree

**Comment by cpsievert** [comment]
Thanks, not sure what's going on, but you can use this link for the time-being http://gallery.shinyapps.io/ggtree

**Comment by friedue** [comment]
thanks, that one seems to work!

**Comment by cpsievert** [comment]
Working now
