### ISSUE TITLE
shinyapps.io

### ISSUE THREAD

**Issue by cpsievert** [cpsievert/shiny_apps#3]
Hey @sckott, 

In [the blog post I did for ropensci](https://ropensci.org/blog/2014/04/16/topic-modeling-in-R/) there is an iframe pointing to shinyapps.io. I don't plan on paying for an account, but I have my own server, so you could use this link --

http://104.131.111.111:3838/LDAelife/

Just FYI, the source for this app is located [here](https://github.com/cpsievert/shiny_apps/tree/master/LDAelife)

**Comment by sckott** [comment]
Good catch. We recently changed to https from http on ropensci.org, so anything thats served over http doesn't work, see devtools in chrome/firefox on https://ropensci.org/blog/2014/04/16/topic-modeling-in-R/ for the error message. 

Would work if you could put https on your server, but I imagine that's too much to ask.  One solution we could do is a screenshot with a link out to the interactive shiny app. Sound okay?

**Comment by cpsievert** [comment]
Sounds good, that'll work for now, I'll have a look at switching to https (although, to be honest, I have no idea how complicated that would be)

**Comment by sckott** [comment]
we just did the https thing, you gotta pay for a ssl certificate, we can help if you want to

Okay, made the change on your blog post, does it look okay? https://ropensci.org/blog/2014/04/16/topic-modeling-in-R/

**Comment by cpsievert** [comment]
Looks great, thanks!

**Comment by cpsievert** [comment]
Of course, as soon as I try to work around the new restrictions, rstudio offers an advocate program...

Since this app is listed in the [shiny user showcase](http://www.rstudio.com/products/shiny/shiny-user-showcase/), they are willing to host it for free (without restrictions), so feel free to go back to an iframe pointing to -- https://gallery.shinyapps.io/LDAelife/

Sorry for the inconvenience @sckott

**Comment by sckott** [comment]
@cpsievert okay, will change it back, no problem
